language: python
python:
- 3.6
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - libdbd-pg-perl
    - postgresql-client
    - build-essential
    - cpanminus
    - perl
    - perl-doc
services:
- docker
install:
- source scripts/install_latest_stable_freenome_build.sh $ANACONDA_TOKEN
- freenome-build develop .
- sudo cpanm --quiet --notest App::Sqitch
cache: pip
script:
- python3 -m flake8 pipeline tests bin
- python3 -m pytest -vv
branches:
  only:
  - master
  - "/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?/"
deploy:
  provider: script
  script:
  - freenome-build deploy -u
  skip_cleanup: true
  on:
    tags: true
  provider: pypi
  user: "nboley"
  password:
    secure: MJ2tTFg+4i0WmaXEglW/8A1aOO3ZV4rrSC4BstOWMzjYm6Dbs3UDIS3IwJ8gzDnX1yQCF2q25+rlHM7w4B/9t8FGgL2Kv8vwuNWx97EOzBjJ78ouf7KMQab0lhsZ4uMpCOXR6ZMa1ChukXZiceHnTwDUBcavduDpPwCDs8GXgglAQdcPLdSK5dM04MAZeukh+yawh8BmWPdtuYy41awiCIxoqupW3MI4ZP4cP4SkrjYd+pt2Pmf4JR/kUia+qnJrTE1IJ1Mh4KKGh06qf82hJGENlebDe5nRnIT3fika5dx1gjBz0/wnvhLxIlAZhNPC1HpLcX5wMw4t1mnj57ntZmaJy8QZwYUItRLKHkI+/hRAQWsSCQaGk1bFBnjuOmKh7XQUrqsK3QjKw4a6H13XudaWvqYmVT3ASIUTgj/HoZ9xEYdUJR0C5Y3K2h7CUb3o2g0RdswmqIynknUfjRLsQiweL3gFdoXXJYIeyYqrazfG70F0CtS8ZCagQquDHVsXYd5ylHV12DVsqmn+0ngnvcXBjMHABS/LUNm32KXCJLzUFK2pcnA4MwCxE8ZjGaTjff56obwZC2ogM27xG30xxMLvf9lSYx3a5/0asg2GJCdY/PKFtM2HdWBjKXstqgKdudRe9y6jizvwjq4rTxRbbeAmCdat1JLNQX9TwnZ7QYE=
  on:
    tags: true
env:
  global:
  - secure: fc0se2Hw0OC2Ws5IF/eSYqaVQZNDMHQu2HQeqmgMZtf1vDO71zJiI9OQtrDOPwQA0vqV7S2tBVDZIs0A/32todp42DNFYUTtrJWRmsqa3JwtMz6RGdSCF7xGeC01kawWj9FLARhHqBdtRCpq40fHfcjn/87c2/yQxqUCrElQ5acu7f2iN92tyjHB3byRvjXK+RXPn4gUeryKtehpMsq6K9ndP5EN3YQdHijkzeT0p2TxfgupJjSdxYDlcLwWkyIBZv975pZW0fBl2AITm7Ih7hFcE071vACveWtR/HYaZqsS29yC8yNXwvBwqTthvPHr4d9B0GKSm1IqArxThWIUkdvkwBgTmPwESjMzHd+Z9L/BHMOMbslp3U+0Uz2ZO8tAUPRXYaeMXsyII/8bL6SuyCHCKvTo3BAiTUktwGgJkl/LmtqXpvBYNhqPL45U2/56T1TQXvp2Rk4s4vfj+INRKJ66VFHF1Osq5kuIw28NdY/TSbhK+RO8sfgQTQj72TVdtvkuj0eAFysCc7f9k1YEyRYwNlO+vhZSWBgrOhuSLvcTUt6ELyOvCDK6D9i7eepAw7hRNVfCOjCYBXXYvXjkeLuw3tGgTYqFg45s3OxemieC0FQAnOYzj0z9cEeFJezKysDXEQXuJ9I6u3SEvq0ZmukPSjzbibB/41NI7XFWc/s=
  - secure: pKeSihZCPsN5PyG68ekyra19Mf3KOk6RP+Ik+J3f0RXV53WiNP3Qt1qLda6ayB6sXC/nDZvpCZNbaTvVx5vrmQhRusQNpcZKn0E8/YrA6NHbdwlJtTub/Qv3sz9PbRAcQz7bWvambQ/sDVirUwdmr42EerTkZEeyU6z4mZv3iXbORPOZGWV/Mfaojz0Z8gKZ7Mp9gij1fedJyHpJOh26TVi+d3Q8fX6GHEUCuh5/cOz1dtvd4DdMJaJ5xrMhI6HGyMRojkuawpnADf4YXkW/SpOB0ex6m6fhm9Uf63V2WaWWkF55W00l9pUvcTyv4BS6ujtr2LaTcLIsCRFv4AqLiRDnBFE6KrL4Yd1MHEBylTXnPHiegCCL04BQjgWK3MAQKP1FaXZ/r9e7O7G0DlGJsvXqMXVH00nClFhvr0Yb++4kBAz1DMUGpDIvss0aJVR4TGrozGy9/SAqx5AgcMnl/YN3dVMFxaWGJfKSQ4MeEGXJFDcI7tHhel2XoWtqAyNvG9CDeB3eInK/qa8NabImdnL1LvEzmWssCO+A1QPH1fJrOfXKIgbvqasaVaRvcAt3aQV+XQpmPNya1tzc/+tRg0tDlx6WBqGsJuWk1vcDzBWkY2npSd+Vtke0Qxf/LAMAYrs9D5DuVvllkopfk/1F399S7HzIKQ1oYsrNimjQbag=
