language: python
sudo: true
os:
- linux
python:
- 3.6
dist: trusty
addons:
  postgresql: '9.6'
  apt:
    packages:
    - libdbd-pg-perl
    - postgresql-client
    - build-essential
    - cpanminus
    - perl
    - perl-doc
services:
- docker
- postgresql
install:
- source scripts/install_latest_stable_freenome_build.sh $ANACONDA_TOKEN freenome_build_env
- source activate freenome_build_env
- freenome-build develop .
- sudo cpanm --quiet --notest App::Sqitch
cache: pip
script:
- make lint
- make test
branches:
  only:
  - master
  - "/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?/"
deploy:
- provider: script
  script: bash scripts/install_and_deploy.sh
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: icS7ePyBFWzzBhZuAQ7l2I2eMmL713uiLqmlKr+Jr6/E3gb4SXUvBgMVWGGJXw5KNeXj4dK9LgTxScqQUEnKKYrB45pi3uElXxdxoSTN37IGhO14dSZHnRBP702+G55kwI6JkJkokPyyELdtvHPa1xlmgEhMp2+zH6fp87/scwFGT2DQmsRCc+oASHHI3liRfHdJ2vSjUEVMnIIWu57ivD9c71cUSl1CfR5Xg2wjszliSoDL3xLYKy5kfPO5j5qCwLNHE/iXIpIBFObVIdfk1yl18KRXb1/X/at/lsIC6ffP8/qhbemcgITRSnHCbrDmqcQDndfIp8rihUdBSUTTEe5OnI3AkxVhkkdJa739OEdyuMQK0239FJvxIWq7x/i7puYwr6qqhHEdOsOoRTGVsPs04NGncC3P/gWdsC8Mg5atMpybaBoAlWDN/+KG0Gv+nn+62y55BL6uxqrIPhiAggF6HjsGqtW6zq8Mb6H3VlyfVwTQPnaYv2h1cHYZLFRTbtVYAmposzwX8zIdC2b4aDkZZF1HXf8Ut5y+zmF919Sjq+V3kqpr9rvHXKpP5vb4at6CvLPpt4GWBzkRemh2qD9AGboDcQBD0Znn/U2mvpF50JAcEwY0aHKo2OB8wW1gzFeUx7x8hG4/nLe1o0bbCm6Bqk88w6U/DDGZZHFIfSo=
