language: python
sudo: true
python:
- 3.6
dist: trusty
script: echo HELLO
install: python setup.py sdist
deploy:
  provider: pypi
  user: nboley
  password:
    secure: kbHDUcCvb77ys2l4BkcNuRqoxRS6TkRby+TPrNKau1JvvRe6SXiOfAKK1a2EPLw3JqPmeeTtImfi0mNlze6ROqOuIfkrnJAFTheb1mwDGuVDdNNRHf48RGnUOLwRUyBhYmBrIdSKJVF5p5KZ5ouXYdccliEll2HL3hKW82Wi8ulxstegPJ+5GdRT8eAAI0wtroZd5Wam1z/bmhmsjAfQ66LgFAiAoodK5WwcW4QV2I0rs7zFwanOq8mqgcTGTSkscwgVsIJ/YUqw6G7rXQG7uvlMkQnuZ/Vc+F4mHeIhA8ZFnZeCZamfZzEw1IJJm6cYZRR2FI5sYicI8Lwkr3oirSd582QFV5nSinS66KzKTr8eqDMgoCGWinXGqJFANCM99AXnsQrIRK045/hJYO1lS5bWuAlsESJeRAPuvi7PKx9CFTf8yNA5rDNeDYBGF/9MiMLxlGfFbzrFrUMb7FWnXJRYDuDg31Giwi9AcgzC1U7xXsv0LiD4Xx9u7HpmN216Mu9PRiQR6czQ83JpGtX3kbBgVtjBdmOCcwZ4tOB/+5sqMLnVbTbqeGfFNnajVeO7JeoglK80Lw0pbNtKm3QW0JRMpDmUegrJx7SzpduzJxr/WqJOlStrbd7UZVqz5ljj9jJ/SQ1oLcbcVRDX/9egwb7eNrjuQCZC5PQYBT6fA48=
