language: python
python:
- 3.6
dist: trusty
script: echo HELLO
install: python setup.py sdist
deploy:
  provider: pypi
  user: nboley
  password:
    secure: R3j0/90fpdkTqfQbCfLqDURub+mF1qcGCjoq2dtwpi9PcbNRuvIrPAfvwL9khbCBaIWYHT/9NvqtHZdZPz01kpanFCUoeljlVtHWB3r6oNPV/+mC68ksZLBrAV3MPYxWX3tOWkJrcm6j8PlgqlgXzVwEC9TMefam/EnyFjFi/vCoEhvKvLM04Ad3b7vqfL09YovAyM3W0FG1dMUecxiQIuxvlRarkiy7mWGmQT8KgaaSPtJxcROMyvVwptlE897hYbWGvkeNiXiKWOd0kspFoIseURcweUou/qtlufvIxh5/IftNbx4SFfEOwjLBNV8wara8G7O53RxCKgnvQ/EOoYVk/iAxdbpN2cIYNrX2AZm1xBW/w5Pvi8GU17ZYcN3tzm0xv0m0mjD7+bAseFkL3ifo3xJGUBvkd20B01aguPo0jwNxvAwwZidPLaHAiFzOkv4QBji9cdULm/rsFoI4r1ziIpVY158B9ri4PCqcSUgM5HSI2rpKYYVDK1gJOKYbD+fho7Rnn7D4KyuL3vS0Bs5Jni8ycFBNHW4g06Eh0juTFvEZlbD8BjbG/P3jl6lCLCaGc3cEDjakU16BnaJlMSDzTxbY7NtyRKv0OuNA/VGGZ3NmdXBJcVbfF9Xv/XQuKi1PgBVMFNZZSacw4sPLy5JMpCzAZWpRMt3feIsL7rs=
