language: python
sudo: true
os:
  - linux
python:
  - 3.6
dist: trusty
sudo: true
addons:
  postgresql: "9.6"
  apt:
    packages:
    - libdbd-pg-perl
    - postgresql-client
    - build-essential
    - cpanminus
    - perl
    - perl-doc
services:
- docker
- postgresql
install:
- source scripts/install_latest_stable_freenome_build.sh $ANACONDA_TOKEN
- freenome-build develop .
- sudo cpanm --quiet --notest App::Sqitch
cache: pip
script:
- make lint
- make test
branches:
  only:
  - master
  - "/v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?/"
deploy:
- provider: script
  script: freenome-build deploy -u
  skip_cleanup: true
  on:
    tags: true
- provider: packagecloud
  repository: python
  username: freenome
  token:
    secure: T7unzDBfe91Hnn9IdrHSMoKG1K1boF5Ybo8ru6X1V+UThDvOmxEgcCggk4z8ZZRvRsP5YI7Q7RoYn1aPEW7G4q/8aYzaMVlPkKqoBw5wLQazbj+FJVajKjKjWDwH5bIGrZYGp3KOnNcFrlSNO5Xf33guIk6JySsGfA+23+uZjiMBne6oNNJFrPU32FHnAv1qxhaP5qrCuYO1N6EaX772iYI8IRF43ib2BO0/wA0dX+azUwKK1YkJTRQf0gnocc9G3eQduX56KI3fVktmouy0vCQj1Pab+UQSBaOQjLaglKBU77Ah+laYALiZv5BZWNsPeRKlzQJyFLOOWO+eJUHZr79vnLZMrGFgv84684mM1KlGoCqcHGaiRuj2wwijyHLqgJe+InmeSyYtb+9rMxgdW8ezUq1D8a+PkEO0b2yZb2eLVj5tGr2yW6VOFrgEyp+D6r/cKxK65IS4PemOeguuR8bpZuiWfKFXvcIBxuL07u02axnqhSz3AHWmfpwZr+ccdD03CfxkvDSotTZWYVFU3+Z43NEAgMVZ7/cyHjqByh0iTHqTPstaQNasnQBeXgDi8q53sH+lKxHydSEVMHJrX/J6a3If1+p0JL0G1YjeSGWbL6Ur1pjiiO9kzwKHyo/oeenZyF0oC+3y7E+zDtXaQ8EO8N1f9lZ/O/7wSA5oYB4=
  on:
    branch: master
  dist: python
  package_glob: dist/*.{whl,zip,egg,egg-info,tar,bz2,Z,gz}
  skip_cleanup: true
#- provider: pypi
#  user: nboley
#  password:
#    secure: kbHDUcCvb77ys2l4BkcNuRqoxRS6TkRby+TPrNKau1JvvRe6SXiOfAKK1a2EPLw3JqPmeeTtImfi0mNlze6ROqOuIfkrnJAFTheb1mwDGuVDdNNRHf48RGnUOLwRUyBhYmBrIdSKJVF5p5KZ5ouXYdccliEll2HL3hKW82Wi8ulxstegPJ+5GdRT8eAAI0wtroZd5Wam1z/bmhmsjAfQ66LgFAiAoodK5WwcW4QV2I0rs7zFwanOq8mqgcTGTSkscwgVsIJ/YUqw6G7rXQG7uvlMkQnuZ/Vc+F4mHeIhA8ZFnZeCZamfZzEw1IJJm6cYZRR2FI5sYicI8Lwkr3oirSd582QFV5nSinS66KzKTr8eqDMgoCGWinXGqJFANCM99AXnsQrIRK045/hJYO1lS5bWuAlsESJeRAPuvi7PKx9CFTf8yNA5rDNeDYBGF/9MiMLxlGfFbzrFrUMb7FWnXJRYDuDg31Giwi9AcgzC1U7xXsv0LiD4Xx9u7HpmN216Mu9PRiQR6czQ83JpGtX3kbBgVtjBdmOCcwZ4tOB/+5sqMLnVbTbqeGfFNnajVeO7JeoglK80Lw0pbNtKm3QW0JRMpDmUegrJx7SzpduzJxr/WqJOlStrbd7UZVqz5ljj9jJ/SQ1oLcbcVRDX/9egwb7eNrjuQCZC5PQYBT6fA48=
#  on:
#    tags: true
env:
  global:
  - secure: fc0se2Hw0OC2Ws5IF/eSYqaVQZNDMHQu2HQeqmgMZtf1vDO71zJiI9OQtrDOPwQA0vqV7S2tBVDZIs0A/32todp42DNFYUTtrJWRmsqa3JwtMz6RGdSCF7xGeC01kawWj9FLARhHqBdtRCpq40fHfcjn/87c2/yQxqUCrElQ5acu7f2iN92tyjHB3byRvjXK+RXPn4gUeryKtehpMsq6K9ndP5EN3YQdHijkzeT0p2TxfgupJjSdxYDlcLwWkyIBZv975pZW0fBl2AITm7Ih7hFcE071vACveWtR/HYaZqsS29yC8yNXwvBwqTthvPHr4d9B0GKSm1IqArxThWIUkdvkwBgTmPwESjMzHd+Z9L/BHMOMbslp3U+0Uz2ZO8tAUPRXYaeMXsyII/8bL6SuyCHCKvTo3BAiTUktwGgJkl/LmtqXpvBYNhqPL45U2/56T1TQXvp2Rk4s4vfj+INRKJ66VFHF1Osq5kuIw28NdY/TSbhK+RO8sfgQTQj72TVdtvkuj0eAFysCc7f9k1YEyRYwNlO+vhZSWBgrOhuSLvcTUt6ELyOvCDK6D9i7eepAw7hRNVfCOjCYBXXYvXjkeLuw3tGgTYqFg45s3OxemieC0FQAnOYzj0z9cEeFJezKysDXEQXuJ9I6u3SEvq0ZmukPSjzbibB/41NI7XFWc/s=
  - secure: pKeSihZCPsN5PyG68ekyra19Mf3KOk6RP+Ik+J3f0RXV53WiNP3Qt1qLda6ayB6sXC/nDZvpCZNbaTvVx5vrmQhRusQNpcZKn0E8/YrA6NHbdwlJtTub/Qv3sz9PbRAcQz7bWvambQ/sDVirUwdmr42EerTkZEeyU6z4mZv3iXbORPOZGWV/Mfaojz0Z8gKZ7Mp9gij1fedJyHpJOh26TVi+d3Q8fX6GHEUCuh5/cOz1dtvd4DdMJaJ5xrMhI6HGyMRojkuawpnADf4YXkW/SpOB0ex6m6fhm9Uf63V2WaWWkF55W00l9pUvcTyv4BS6ujtr2LaTcLIsCRFv4AqLiRDnBFE6KrL4Yd1MHEBylTXnPHiegCCL04BQjgWK3MAQKP1FaXZ/r9e7O7G0DlGJsvXqMXVH00nClFhvr0Yb++4kBAz1DMUGpDIvss0aJVR4TGrozGy9/SAqx5AgcMnl/YN3dVMFxaWGJfKSQ4MeEGXJFDcI7tHhel2XoWtqAyNvG9CDeB3eInK/qa8NabImdnL1LvEzmWssCO+A1QPH1fJrOfXKIgbvqasaVaRvcAt3aQV+XQpmPNya1tzc/+tRg0tDlx6WBqGsJuWk1vcDzBWkY2npSd+Vtke0Qxf/LAMAYrs9D5DuVvllkopfk/1F399S7HzIKQ1oYsrNimjQbag=
