language: python
python:
- 3.6
dist: trusty
script: echo HELLO
install: python setup.py sdist
deploy:
  provider: pypi
  user: nboley
  password: freenome
#    secure: fdW2Eyd57an/jq7xpJuQdIqWRC+dHnDc+Go4k+XcXMc0tH8+FXU8VymlMJgidM3WN+C/6zobZo+ISJZp4W89h2oOQrYc+k2bDgz904TA9HHmHjt6UpoXK6EAhh3zYcEbcU93Myim5ofSrolz/IsomYSdjWqIfH/L0D52dBUbV1YSgA9dfEMBdIr3y75aL6FsGVGFTv5owMjq1QgCCupV0vkEtL2TGnW#Jotv7BsPcMuSXepKsfMlzFSmBmgxaEaDSg9pJl8lcE2m3j2VdU6il6GmUoHmh+mdh/DUYoDT4Fxm4dIJJ7aAMU0CaA+ZMizyfPhEzK2hc0FULGr80QIeoqeS4FmZXaWjpZNrvC3cF4Vdn2VOfspP4qrYelfvCsYkBOIqmeyIAlKMQYrnqoB/xwW5uRy5EEm2k0xRG/aqGWkonHWPveqTbBzPRvlvOqxkK31PZABxiLJ#I3LZpagQ+H4kpieZpiQE1Xe4cIh0oFNmrJ51P/RcQvjEtueNC8A+h/or0ckteLSHT65sUtpdcMe12wFpgrVj5bNZKSny8Jt8iJ76JjZrow71cWaP3gpdmQdUjvLjAmc37p9ROaPxvdQ+U2MtjlhTD4YzOe5ysjq4vG8ZLMtwxDEZAgfHXEUHKiPjQZ87haHqhJ8WK+wGpd9T++wGBW0+TMaHfMQ/o9QUc=
