package:
  name: freenome-build
  version: {{ VERSION }}

source:
  git_url: ..

requirements:
  build:
    - conda
    - conda-build
    - conda-verify

channels:
  - bioconda
  - conda-forge
  - freenome
