package:
  name: freenome-build
  version: {{ VERSION }}

source:
  path: ..

requirements:
  build:
    - conda
    - conda-build
    - conda-verify
    - setuptools

  run:
    - conda
    - conda-build
    - conda-verify

channels:
  - bioconda
  - conda-forge
  - freenome

build:
  entry_points:
    - freenome_build = freenome_build.freenome_build:main
  preserve_egg_dir: True
