package:
  name: freenome-build
  version: {{ VERSION }}

source:
  path: ..

requirements:
  host:
    - python {{PY_VER}}*

  build:
    - setuptools
    - flake8
    - jinja2
    - pyyaml

  run:
    - python
    - conda
    - conda-build
    - conda-verify

channels:
  - bioconda
  - conda-forge
  - freenome

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
